# Generated by Django 4.1.5 on 2023-11-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_calls_customuser_is_talking'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiting_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='calls',
        ),
    ]
