# Generated by Django 4.1.5 on 2023-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usercommunication_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCommunication',
        ),
        migrations.AddField(
            model_name='waiting_users',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiting_users',
            name='d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waiting_users',
            name='offer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
