# Generated by Django 4.1.5 on 2023-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_usercommunication_waiting_users_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.JSONField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('d', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='waiting_users',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='waiting_users',
            name='d',
        ),
        migrations.RemoveField(
            model_name='waiting_users',
            name='offer',
        ),
    ]
