# Generated by Django 4.1.5 on 2023-12-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_customuser_friends_customuser_is_talking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_talking',
        ),
    ]
