# Generated by Django 4.1.5 on 2023-12-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_friendship_friendship_sender_receiver_not_same_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='sender_receiver_not_same',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
