# Generated by Django 4.1.5 on 2023-12-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_friendship_sender_receiver_not_same_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunication_text',
            name='ice_candidate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
