# Generated by Django 4.1.5 on 2023-12-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_usercommunication_text_ice_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiting_users_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100000)),
                ('peer_id', models.CharField(max_length=100000)),
            ],
        ),
    ]
