# Generated by Django 4.1.5 on 2024-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_waiting_users_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='connectedmfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conecteds', models.IntegerField(null=True)),
            ],
        ),
    ]
