# Generated by Django 4.1.5 on 2024-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_connectedmfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiting_users_test_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100000)),
                ('peer_id', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='connectedmfs',
        ),
    ]
